package com.procurement.smart_procurement.controller;

import com.procurement.smart_procurement.service.VendorService;
import com.procurement.smart_procurement.service.report.ReportService;
import net.sf.jasperreports.engine.JRException;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;

/**
 * ReportController
 * --------------------------------------------------
 * Handles report generation APIs.
 */
@RestController
@RequestMapping("/api/v1/reports")
public class ReportController {

    private final ReportService reportService;
    private final VendorService vendorService;

    public ReportController(
            ReportService reportService,
            VendorService vendorService
    ) {
        this.reportService = reportService;
        this.vendorService = vendorService;
    }

    /**
     * Generate Vendor Report PDF
     */
    @GetMapping("/vendors")
    public ResponseEntity<byte[]> generateVendorReport()
            throws JRException {

        // 1️⃣ Fetch vendor report data
        var vendorReportData =
                vendorService.getVendorReportData();

        // 2️⃣ Use MUTABLE map for JasperReports
        Map<String, Object> params = new HashMap<>();

        // Report title
        params.put("REPORT_TITLE", "Vendor Report");

        // Report generated date
        params.put("GENERATED_DATE",
                java.time.LocalDate.now().toString()
        );

        // Report generated by (role / user)
        params.put("GENERATED_BY", "ADMIN");


        // 3️⃣ Generate PDF
        byte[] pdfReport =
                reportService.generateReport(
                        "/reports/vendor_report.jrxml",
                        vendorReportData,
                        params
                );

        // 4️⃣ Return PDF response
        return ResponseEntity.ok()
                .header(
                        HttpHeaders.CONTENT_DISPOSITION,
                        "inline; filename=vendor_report.pdf"
                )
                .contentType(MediaType.APPLICATION_PDF)
                .body(pdfReport);
    }
}
